### ISSUE TITLE
请问要怎么安装vue2.x可用的vue-minder

### ISSUE THREAD

**Issue by DengJianShen** [hexyun/vue-minder#2]
如题，我直接通过cnpm安装的包，好像只支持1.x版本

**Comment by jiangtao** [comment]
2.x我还没开始搞， 有兴趣可以一块搞。 原理很简单， 就是把1.x里面的api 迁移到2.x即可。 

里面涉及的api，生命周期， refs等

**Comment by jiangtao** [comment]
具体的计划可以看 [Vue2.x计划](https://github.com/hexyun/vue-minder/issues/3)
