### ISSUE TITLE
vue2.0

### ISSUE THREAD

**Issue by NO-MAP** [hexyun/vue-minder#4]
你好，有关于vue2.0+的迁移demo么

**Comment by jiangtao** [comment]
迁移的方案 我有准备 就是改变vue的生命周期和打包配置就可以。 只是最近工作比较忙 没有升级。

**Comment by jiangtao** [comment]
2.0迁移版本: https://github.com/jiangtao/minder-upgrade 目前只是搭了项目脚手架，里面还有不少细节没改动。 当迁移完毕后， 关注本repo 2.0分支， 预计11月15日迁移完毕。
