### ISSUE TITLE
看不到其他分支！

### ISSUE THREAD

**Issue by ameibj** [hexyun/vue-minder#6]
现在只能看到 master分支，我想看vue 2.0+ 的示例是看不到的。

**Comment by jiangtao** [comment]
https://github.com/jiangtao/minder-upgrade 
因为是平常维护， 目前代码还没改完， 先在这个repo改完，跑通了且修改完后会同步到这个repo上。

感谢关注。

**Comment by jiangtao** [comment]
升级到最新的 vue3.x，已经合并到 master 了。
